import { peerManager } from './peer-manager.js';
import { sendFiles, receiveFiles, downloadFile, requestNotificationPermission } from './transfer-engine.js';
import { addTransfer, getTransfers, clearTransfers } from './history-db.js';
import { formatFileSize, formatSpeed, formatTime, formatDate } from './utils.js';
import QRCode from 'qrcode';

const root=document.getElementById('app');
let view='home'; let unsubscribe=null; let peerState={}; let scanner=null;
const blankProgress={fileIndex:0,fileName:'',fileProgress:0,totalProgress:0,totalSent:0,totalReceived:0,totalSize:0,speed:0,elapsed:0};

function icon(path,cls='nv-w-5 nv-h-5'){return `<svg class="${cls}" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="${path}"/></svg>`;}
function setView(v){stopScanner();view=v;location.hash=v==='home'?'':v;render();}
function handleHash(){const h=location.hash.slice(1);view=h==='send'||h==='receive'?h:'home';render();}
window.addEventListener('hashchange',handleHash);

async function render(){
  if(view==='home') await renderHome(); else if(view==='send') renderSend(); else renderReceive();
}
function shell(title,color,body,device=''){return `<div class="nv-min-h-screen nv-flex nv-flex-col nv-px-4 nv-py-6 nv-max-w-lg nv-mx-auto"><div class="nv-flex nv-items-center nv-gap-3 nv-mb-6"><button id="back" class="nv-w-10 nv-h-10 nv-rounded-xl nv-bg-nyalur-surface nv-flex nv-items-center nv-justify-center nv-active-scale-95">${icon('M15 19l-7-7 7-7')}</button><div><h1 class="nv-text-xl nv-font-bold ${color}">${title}</h1>${device?`<span class="nv-text-xs nv-text-nyalur-muted-60">${escapeHtml(device)}</span>`:''}</div>${peerState.status==='connected'?`<span class="nv-ml-auto nv-text-xs ${color}-60 nv-flex nv-items-center nv-gap-1"><span class="nv-w-2 nv-h-2 nv-rounded-full ${color==='nv-text-nyalur-green'?'nv-bg-nyalur-green':'nv-bg-nyalur-orange'}"></span>Online</span>`:''}</div>${body}</div>`;}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function bindBack(){document.getElementById('back')?.addEventListener('click',()=>setView('home'));}

async function renderHome(){
  const device=localStorage.getItem('nyalur-device-name')||''; const history=await getTransfers(20);
  root.innerHTML=`<div class="nv-flex nv-flex-col nv-items-center nv-min-h-screen nv-px-4 nv-py-8"><div class="nv-mt-6 nv-mb-2 nv-text-center"><h1 class="nv-text-5xl nv-font-black nv-tracking-tight"><span class="nv-text-nyalur-green">NYA</span><span class="nv-text-nyalur-orange">LUR</span></h1><p class="nv-text-nyalur-muted nv-text-sm nv-mt-2 nv-tracking-wide">Salurkan file, langsung sampai.</p></div><div class="nv-mt-3 nv-mb-2" id="nameArea"></div><div class="nv-flex nv-gap-4 nv-mt-8 nv-mb-10 nv-w-full nv-max-w-sm nv-justify-center"><button id="sendBtn" class="home-action green"><span>${icon('M7 11l5-5m0 0l5 5m-5-5v12','nv-w-12 nv-h-12')}</span><b>KIRIM</b></button><button id="receiveBtn" class="home-action orange"><span>${icon('M17 13l-5 5m0 0l-5-5m5 5V6','nv-w-12 nv-h-12')}</span><b>TERIMA</b></button></div><div class="nv-w-full nv-max-w-sm">${history.length?`<div class="nv-flex nv-items-center nv-justify-between nv-mb-3"><h2 class="nv-text-nyalur-muted nv-text-xs nv-uppercase nv-tracking-widest">◷ RIWAYAT (${history.length})</h2><button id="clearHistory" class="nv-text-xs nv-text-nyalur-muted">Hapus</button></div><div class="nv-space-y-2">${history.map(r=>`<div class="nv-bg-nyalur-surface nv-rounded-xl nv-p-3 nv-flex nv-items-center nv-gap-3"><div class="nv-w-8 nv-h-8 nv-rounded-lg nv-bg-nyalur-green-15 nv-flex nv-items-center nv-justify-center">${r.direction==='sent'?icon('M7 11l5-5m0 0l5 5m-5-5v12','nv-w-4 nv-h-4 nv-text-nyalur-green'):icon('M17 13l-5 5m0 0l-5-5m5 5V6','nv-w-4 nv-h-4 nv-text-nyalur-orange')}</div><div class="nv-flex-1 nv-min-w-0"><p class="nv-text-sm nv-truncate">${escapeHtml(r.files?.map(f=>f.name).join(', ')||'File')}</p><p class="nv-text-xs nv-text-nyalur-muted">${r.direction==='sent'?'→':'←'} ${escapeHtml(r.peerName||'—')} · ${formatFileSize(r.totalSize)} · ${formatDate(r.timestamp)}</p></div><span class="nv-text-xs nv-text-nyalur-green">${r.status==='completed'?'✓':'✗'}</span></div>`).join('')}</div>`:`<div class="nv-text-center nv-py-8"><div class="nv-w-16 nv-h-16 nv-rounded-2xl nv-bg-nyalur-surface nv-flex nv-items-center nv-justify-center nv-mx-auto nv-mb-4">${icon('M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12','nv-w-8 nv-h-8 nv-text-nyalur-muted-30')}</div><p class="nv-text-nyalur-muted-40 nv-text-sm">Belum ada transfer</p><p class="nv-text-nyalur-muted-25 nv-text-xs nv-mt-1">Mulai kirim atau terima file!</p></div>`}</div><div class="nv-mt-auto nv-pt-8 nv-pb-4"><p class="nv-text-nyalur-muted-30 nv-text-xs">Nyalur v0.4.0 · P2P · Tanpa iklan · Tanpa kuota</p></div></div>`;
  document.getElementById('sendBtn').onclick=()=>setView('send'); document.getElementById('receiveBtn').onclick=()=>setView('receive');
  const area=document.getElementById('nameArea'); area.innerHTML=`<button id="editName" class="nv-text-nyalur-muted-60 nv-text-xs">▣ ${escapeHtml(device||'Perangkat')}　✎</button>`;document.getElementById('editName').onclick=()=>{area.innerHTML=`<input id="nameInput" maxlength="20" value="${escapeHtml(device)}" class="nv-bg-nyalur-surface nv-border nv-border-nyalur-border nv-rounded-lg nv-px-3 nv-py-1-5 nv-text-sm nv-text-center"/> <button id="saveName" class="nv-text-nyalur-green">OK</button>`;document.getElementById('nameInput').focus();document.getElementById('saveName').onclick=saveName;document.getElementById('nameInput').onkeydown=e=>{if(e.key==='Enter')saveName();if(e.key==='Escape')renderHome();};};
  function saveName(){const n=document.getElementById('nameInput').value.trim().slice(0,20);if(n){localStorage.setItem('nyalur-device-name',n);}renderHome();}
  document.getElementById('clearHistory')?.addEventListener('click',async()=>{if(confirm('Hapus semua riwayat transfer?')){await clearTransfers();renderHome();}});
}

function initPeerSender(){if(unsubscribe)unsubscribe();unsubscribe=peerManager.subscribe(s=>{peerState=s;});return peerManager.init();}
function renderSend(){
  let files=[];let state='idle';let progress={...blankProgress};let error='';let result=null;let device=localStorage.getItem('nyalur-device-name')||peerManager.getDeviceName();
  root.innerHTML=shell('KIRIM FILE','nv-text-nyalur-green',`<div id="sendBody"></div>`,device);bindBack();initPeerSender().then(()=>requestNotificationPermission()).catch(e=>{error=e.message;state='error';update();});update();
  function update(){const body=document.getElementById('sendBody');if(!body)return;
    if(state==='error'){body.innerHTML=errorView('Gagal',error,'Coba Lagi');document.getElementById('retry').onclick=()=>{state='idle';error='';update();initPeerSender();};return;}
    if(state==='complete'){body.innerHTML=`<div class="center-page"><div class="success-icon green">✓</div><h2>Berhasil!</h2><p>${result?.files.length||files.length} file (${formatFileSize(result?.totalSize||0)}) terkirim dalam ${formatTime((result?.duration||0)/1000)}</p><p>Kecepatan rata-rata: ${formatSpeed((result?.totalSize||0)/((result?.duration||1)/1000))}</p><button id="again" class="nv-px-8 nv-py-3 nv-bg-nyalur-surface nv-rounded-xl">Kirim Lagi</button></div>`;document.getElementById('again').onclick=()=>{files=[];result=null;progress={...blankProgress};state='idle';update();};return;}
    if(state==='transferring'){body.innerHTML=progressView(progress,'green');return;}
    if(state==='scanning'){body.innerHTML=`<div class="center-page"><p>Arahkan kamera ke QR Code</p><div id="qr-reader" class="scanner"></div><button id="stopScan" class="nv-px-6 nv-py-3 nv-bg-nyalur-surface nv-rounded-xl">Batal</button></div>`;document.getElementById('stopScan').onclick=stopScanner;startScanner(code=>{document.getElementById('room').value=code;stopScanner();state='idle';update();});return;}
    body.innerHTML=`<label class="drop-zone"><div>${icon('M12 4.5v15m7.5-7.5h-15','nv-w-10 nv-h-10 nv-text-nyalur-muted')}<p>Tap untuk pilih file</p><small>Foto, video, dokumen — semua jenis file</small></div><input id="fileInput" type="file" multiple hidden></label>${files.length?`<div class="file-list">${files.map((f,i)=>`<div class="file-row"><span>${escapeHtml(f.name)}<small>${formatFileSize(f.size)}</small></span><button data-i="${i}" class="remove">×</button></div>`).join('')}<p class="file-total">${files.length} file · Total: ${formatFileSize(files.reduce((s,f)=>s+f.size,0))}</p></div><label class="field-label">Kode Room Penerima</label><div class="code-row"><input id="room" maxlength="4" placeholder="XXXX"><button id="scan">QR</button></div><button id="connect" class="primary green">Kirim</button>`:''}`;
    document.getElementById('fileInput').onchange=e=>{files.push(...Array.from(e.target.files));update();};document.querySelectorAll('.remove').forEach(b=>b.onclick=()=>{files.splice(+b.dataset.i,1);update();});document.getElementById('scan')?.addEventListener('click',()=>{if(!files.length)return;state='scanning';update();});document.getElementById('connect')?.addEventListener('click',connect);
  }
  async function connect(){const room=document.getElementById('room').value.toUpperCase().replace(/[^A-Z0-9]/g,'');if(room.length!==4||!files.length)return;state='connecting';update();try{const conn=await peerManager.connectToRoom(room);state='transferring';update();result=await sendFiles(conn,files,p=>{progress=p;update();});await addTransfer({direction:'sent',peerName:room,files:result.files,totalSize:result.totalSize,duration:result.duration,status:'completed'});state='complete';update();}catch(e){error=e.message||'Transfer gagal';await addTransfer({direction:'sent',peerName:room,files:files.map(f=>({name:f.name,size:f.size})),totalSize:files.reduce((s,f)=>s+f.size,0),duration:progress.elapsed,status:'failed'});state='error';update();}}
}
function renderReceive(){
  let state='waiting',offer=null,receiver=null,receivedFiles=[],transferResult=null,error='',progress={...blankProgress},copied=false;let device=localStorage.getItem('nyalur-device-name')||peerManager.getDeviceName();
  root.innerHTML=shell('TERIMA FILE','nv-text-nyalur-orange',`<div id="receiveBody"></div>`,device);bindBack();if(unsubscribe)unsubscribe();unsubscribe=peerManager.subscribe(s=>{peerState=s;update();});peerManager.initAsReceiver().then(async r=>{await requestNotificationPermission();const url=await QRCode.toDataURL(r.roomCode,{width:220,margin:2,color:{dark:'#FF6B00',light:'#0F172A'},errorCorrectionLevel:'M'});document.getElementById('receiveBody')?.setAttribute('data-qr',url);update();}).catch(e=>{error=e.message;state='error';update();});peerManager.onIncomingConnection(conn=>{receiver=receiveFiles(conn,o=>{offer=o;state='incoming';update();},p=>{progress=p;state='receiving';update();},(info,blob)=>{receivedFiles.push({...info,blob});},async r=>{transferResult=r;state='complete';await addTransfer({direction:'received',peerName:offer?.deviceName||'Unknown',files:r.files.map(f=>({name:f.name||'',size:f.size||0})),totalSize:r.totalSize,duration:r.duration,status:'completed'});update();});});update();
  function update(){const body=document.getElementById('receiveBody');if(!body)return;const qr=body.dataset.qr;
    if(state==='error'){body.innerHTML=errorView('Error',error,'Kembali');document.getElementById('retry').onclick=()=>setView('home');return;}
    if(state==='incoming'){body.innerHTML=`<div class="center-page"><div class="success-icon orange">↓</div><h2>Transfer Masuk</h2><p>dari <b>${escapeHtml(offer?.deviceName||'Pengirim')}</b></p><div class="offer-box">${(offer?.files||[]).map(f=>`<div>${escapeHtml(f.name)} <small>${formatFileSize(f.size)}</small></div>`).join('')}<hr><b>Total: ${formatFileSize(offer?.totalSize||0)}</b></div><div class="two-buttons"><button id="reject">Tolak</button><button id="accept" class="primary orange">Terima</button></div></div>`;document.getElementById('accept').onclick=()=>{receiver.accept();state='receiving';update();};document.getElementById('reject').onclick=()=>{receiver.reject();offer=null;receiver=null;state='waiting';update();};return;}
    if(state==='receiving'){body.innerHTML=progressView(progress,'orange');return;}
    if(state==='complete'){body.innerHTML=`<div class="center-page"><div class="success-icon orange">✓</div><h2>Diterima!</h2><p>${transferResult?.files.length||0} file (${formatFileSize(transferResult?.totalSize||0)}) dalam ${formatTime((transferResult?.duration||0)/1000)}</p><div class="offer-box">${receivedFiles.map((f,i)=>`<div>${escapeHtml(f.name)} <button class="download" data-i="${i}">Unduh</button></div>`).join('')}</div><button id="again" class="nv-px-8 nv-py-3 nv-bg-nyalur-surface nv-rounded-xl">Terima Lagi</button></div>`;document.querySelectorAll('.download').forEach(b=>b.onclick=()=>downloadFile(receivedFiles[+b.dataset.i].blob,receivedFiles[+b.dataset.i].name));document.getElementById('again').onclick=()=>{state='waiting';offer=null;receiver=null;receivedFiles=[];transferResult=null;peerManager.onIncomingConnection(handleIncoming);update();};return;}
    body.innerHTML=`<div class="receive-wait"><p class="nv-text-xs nv-text-nyalur-muted">KODE ROOM</p><div class="room-code">${peerState.roomCode?peerState.roomCode.split('').join(' '):'....'}</div><p>Berikan kode ini ke pengirim</p>${qr?`<img class="qr" src="${qr}" alt="QR Code room">`:''}<button id="copy" class="secondary">${copied?'Tersalin!':'Salin Kode'}</button><p>Menunggu koneksi...</p></div>`;document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(peerState.roomCode);copied=true;update();setTimeout(()=>{copied=false;update();},2000);}catch{}};
  }
  function handleIncoming(conn){receiver=receiveFiles(conn,o=>{offer=o;state='incoming';update();},p=>{progress=p;state='receiving';update();},(i,b)=>receivedFiles.push({...i,blob:b}),async r=>{transferResult=r;state='complete';await addTransfer({direction:'received',peerName:offer?.deviceName||'Unknown',files:r.files.map(f=>({name:f.name||'',size:f.size||0})),totalSize:r.totalSize,duration:r.duration,status:'completed'});update();});}
}
function progressView(p,theme){const pct=Math.round((p.totalProgress||0)*100);return `<div class="center-page"><div class="progress-circle ${theme}" style="--p:${pct}%">${pct}%</div><p class="nv-text-sm">${escapeHtml(p.fileName||'Transfer file...')}</p><div class="progress-bar"><div class="${theme}" style="width:${pct}%"></div></div><div class="progress-meta"><span>${formatFileSize(p.totalSent||p.totalReceived||0)} / ${formatFileSize(p.totalSize||0)}</span><span>${formatSpeed(p.speed||0)}</span></div>${p.speed>0?`<small>~${formatTime(((p.totalSize||0)-(p.totalSent||p.totalReceived||0))/p.speed)} lagi</small>`:''}</div>`;}
function errorView(title,msg,button){return `<div class="center-page"><div class="success-icon error">!</div><h2>${title}</h2><p>${escapeHtml(msg)}</p><button id="retry" class="nv-px-6 nv-py-3 nv-bg-nyalur-surface nv-rounded-xl">${button}</button></div>`;}
async function startScanner(onCode){try{const {Html5Qrcode}=await import('html5-qrcode');scanner=new Html5Qrcode('qr-reader');await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:200,height:200},aspectRatio:1},text=>{let c=text.trim().replace(/^nyalur-/i,'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,4);if(c.length===4)onCode(c);},()=>{});}catch(e){alert('Tidak bisa membuka kamera: '+(e.message||e));stopScanner();}}
async function stopScanner(){if(scanner){try{await scanner.stop();scanner.clear();}catch{}scanner=null;}}

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));}
handleHash();
